num1 = int(input("숫자를 입력하시오 : "))
num2 = int(input("숫자를 입력하시오 : ")) # 타입 캐스팅까지 한번에
print()
print(f"{num1} + {num2} = {num1+num2}")
print(f"{num1} - {num2} = {num1-num2}")
print(f"{num1} * {num2} = {num1*num2}")
print(f"{num1} / {num2} = {num1/num2}")
print(f"{num1} // {num2} = {num1//num2}")
print(f"{num1} % {num2} = {num1%num2}")
print(f"{num1} ** {num2} = {num1**num2}")
print()
print(f"{num1} > {num2} = {num1>num2}")
print(f"{num1} < {num2} = {num1<num2}")
print(f"{num1} >= {num2} = {num1>=num2}")
print(f"{num1} < {num2} = {num1<=num2}")
print(f"{num1} == {num2} = {num1==num2}")
print(f"{num1} != {num2} != {num1>num2}")
print()
max_val = int(input("숫자를 입력하시오 : "))
min_val = int(input("숫자를 입력하시오 : "))
print(f"{num1}>{num2} and {num1}>{max_val}    => {num1>max_val}")
print(f"{num1}>{num2} and {num1}>{min_val}    => {num1>min_val}")
print(f"not {num1}    => {not num1}")